// js/pastSheets.js
import { $, customAlert, formatDateForDisplay } from './utils.js';
import { apiCall } from './apiClient.js';

export function setupPastSheetsModal(getEmployeesFunc, btnId) {
    const btn = $(btnId);
    const modal = $('viewSheetsModal');
    const closeBtn = $('closePastSheetsModal');
    const listContainer = $('pastSheetsList');

    if (btn) {
        btn.addEventListener('click', async () => {
            modal.classList.remove('hidden');
            listContainer.innerHTML = '<div class="text-center py-4">Loading...</div>';
            await loadPastSheets();
        });
    }

    if (closeBtn) closeBtn.addEventListener('click', () => modal.classList.add('hidden'));

    async function loadPastSheets() {
        try {
            const sheets = await apiCall('getSalaryArchive', 'GET', null, { metaOnly: 'true' });
            renderSheetList(sheets);
        } catch (error) {
            console.error(error);
            listContainer.innerHTML = '<div class="text-center py-4 text-red-500">Failed to load past sheets.</div>';
        }
    }

    function renderSheetList(sheets) {
        listContainer.innerHTML = '';
        if (!sheets || sheets.length === 0) {
            listContainer.innerHTML = '<div class="text-center py-4 text-gray-500">No past salary sheets found.</div>';
            return;
        }
        sheets.sort((a, b) => b.monthYear.localeCompare(a.monthYear));
        sheets.forEach(sheet => {
            const item = document.createElement('div');
            item.className = 'flex justify-between items-center p-4 bg-gray-50 rounded border';

            const dateObj = new Date(sheet.timestamp);
            const dateStr = dateObj.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase();
            const timeStr = dateObj.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
            const fullDateTime = `${dateStr} at ${timeStr}`;

            item.innerHTML = `
                <div>
                    <p class="font-semibold text-gray-800">${sheet.monthYear}</p>
                    <p class="text-xs text-gray-500">
                        Generated by: <span class="font-medium text-gray-700">${sheet.generatedBy || 'Unknown'}</span>
                    </p>
                    <p class="text-xs text-gray-400 mt-0.5">
                        ${fullDateTime}
                    </p>
                </div>
            `;
            const btnDiv = document.createElement('div');
            const dBtn = document.createElement('button');
            dBtn.className = 'btn btn-sm btn-primary ml-2';
            dBtn.innerHTML = '<i class="fas fa-download mr-1"></i> ZIP';
            dBtn.addEventListener('click', () => downloadSheetZip(sheet));
            btnDiv.appendChild(dBtn);
            item.appendChild(btnDiv);
            listContainer.appendChild(item);
        });
    }

    function getFormattedMonthYear(dateStr) {
        let date;
        const shortYearMatch = dateStr.match(/^([A-Za-z]+)[^A-Za-z0-9](\d{2})$/);
        if (shortYearMatch) {
            const monthStr = shortYearMatch[1];
            const yearVal = parseInt(shortYearMatch[2], 10);
            const fullYear = 2000 + yearVal;
            date = new Date(`${monthStr} 01, ${fullYear}`);
        } else {
            date = new Date(dateStr + "-01");
        }
        if (isNaN(date.getTime())) date = new Date(dateStr);
        if (isNaN(date.getTime())) return { full: dateStr, quote: dateStr };
        const month = date.toLocaleString('default', { month: 'long' });
        const year = date.getFullYear();
        return { full: `${month}-${year}`, quote: `${month}'${year}` };
    }

    function convertNumberToWords(amount) {
        const units = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
        const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
        const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

        if (amount === 0) return "Zero";

        const numToString = (n) => {
            let str = "";
            if (n > 99) { str += units[Math.floor(n / 100)] + " Hundred "; n %= 100; }
            if (n > 19) { str += tens[Math.floor(n / 10)] + " "; n %= 10; }
            if (n > 9) { str += teens[n - 10] + " "; n = 0; }
            if (n > 0) { str += units[n] + " "; }
            return str.trim();
        };

        const convert = (num) => {
            if (num === 0) return "";
            let words = "";
            const crore = Math.floor(num / 10000000); num %= 10000000;
            if (crore > 0) words += numToString(crore) + " Crore ";
            const lakh = Math.floor(num / 100000); num %= 100000;
            if (lakh > 0) words += numToString(lakh) + " Lakh ";
            const thousand = Math.floor(num / 1000); num %= 1000;
            if (thousand > 0) words += numToString(thousand) + " Thousand ";
            if (num > 0) words += numToString(num);
            return words.trim();
        };
        return convert(Math.floor(amount)) + " Only";
    }

    // Helper: isSeparatedInMonth (Copied logic from salarySheet.js for consistency)
    function isSeparatedInMonth(dateStr, monthVal) {
        if (!dateStr) return false;
        let d = new Date(dateStr);
        if (isNaN(d.getTime())) return false;
        const yyyy = d.getFullYear();
        const mm = String(d.getMonth() + 1).padStart(2, '0');
        return `${yyyy}-${mm}` === monthVal;
    }

    async function downloadSheetZip(sheetMeta) {
        try {
            customAlert("Please Wait", "Fetching full data (this may take a moment)...");

            let allEmployees = [];
            let offset = 0;
            const LIMIT = 500;
            let hasMore = true;

            while (hasMore) {
                const resp = await apiCall('getSalaryArchive', 'GET', null, {
                    monthYear: sheetMeta.monthYear,
                    limit: LIMIT,
                    offset: offset
                });

                if (!resp || resp.length === 0) {
                    if (offset === 0) throw new Error("No data found.");
                    break;
                }

                const batchData = resp[0].jsonData;
                const totalRecords = resp[0].totalRecords || batchData.length;

                if (Array.isArray(batchData)) {
                    allEmployees = allEmployees.concat(batchData);
                    if (batchData.length < LIMIT || allEmployees.length >= totalRecords) {
                        hasMore = false;
                    } else {
                        offset += LIMIT;
                    }
                } else {
                    allEmployees = [batchData];
                    hasMore = false;
                }
            }

            const { full, quote } = getFormattedMonthYear(sheetMeta.monthYear);
            const accountingFmt0 = '_(* #,##0_);_(* (#,##0);_(* "-"_);_(@_)';
            const zip = new JSZip();

            const projectGroups = {};
            const getVal = (v) => (v !== undefined && v !== null) ? Number(v) : 0;
            const getStr = (v) => (v !== undefined && v !== null) ? String(v) : '';

            allEmployees.forEach(emp => {
                const p = emp.reportProject || 'Unknown';
                const s = emp.subCenter || 'General';
                if (!projectGroups[p]) projectGroups[p] = {};
                if (!projectGroups[p][s]) projectGroups[p][s] = { active: [], hold: [], separated: [] };

                let listCategory = null;
                const isHeld = (emp.salaryHeld === true || String(emp.salaryHeld).toUpperCase() === 'TRUE');

                if (isHeld) {
                    listCategory = 'hold';
                } else if ((emp.status === 'Resigned' || emp.status === 'Terminated') && isSeparatedInMonth(emp.separationDate, sheetMeta.monthYear)) {
                    listCategory = 'separated';
                } else if (emp.status === 'Active' || !emp.status) { // Default active if missing
                    listCategory = 'active';
                } else {
                    return;
                }
                projectGroups[p][s][listCategory].push(emp);
            });

            // Same helper function as salarySheet.js
            function addSalarySheetTab(workbook, sheetName, dataBySubCenter, categoryKey) {
                const sheet = workbook.addWorksheet(sheetName, { views: [{ state: 'frozen', ySplit: 4 }] });

                sheet.mergeCells('A1:AU1');
                const r1 = sheet.getCell('A1');
                r1.value = "Metal Plus Limited";
                r1.font = { bold: true, size: 16, name: 'Calibri' };
                r1.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };

                sheet.mergeCells('A2:AU2');
                const r2 = sheet.getCell('A2');
                r2.value = `${sheetName} - for the Month of ${full}`;
                r2.font = { bold: true, size: 12, name: 'Calibri' };
                r2.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };

                [
                    { r: 'A3:J3',  t: 'Employee Information' },
                    { r: 'K3:Q3',  t: 'Attendance' },
                    { r: 'R3:U3',  t: 'Salary Structure' },
                    { r: 'V3:AD3', t: 'Earnings & Benefits' },
                    { r: 'AE3:AO3',t: 'Deductions' },
                    { r: 'AP3:AU3',t: 'Payment Information' },
                ].forEach(m => {
                    sheet.mergeCells(m.r);
                    const cell = sheet.getCell(m.r.split(':')[0]);
                    cell.value = m.t;
                    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
                    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
                    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
                    cell.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                });

                const headers = [
                    "SL","ID","Name","Designation","Functional Role","Joining Date","Project","Project Office","Report Project","Sub Center",
                    "Total Working Days","Holidays","Availing Leave","LWP","Actual Present","Net Present","OT Hours",
                    "Previous Salary","Basic","Others","Gross Salary",
                    "Motobike / Car Maintenance Allowance","Laptop Rent","Others Allowance","Arrear","Food Allowance","Station Allowance","Hardship Allowance","OT Amount","Gross Payable Salary",
                    "Gratuity","Subsidized Lunch","TDS","Motorbike Loan","Welfare Fund","Salary/ Others Loan","Subsidized Vehicle","CPF","Others Adjustment","Attendance Deduction","Total Deduction",
                    "Cash Payment", "Account Payment", "Net Salary Payment", "Bank Account Number","Payment Type","Remarks"
                ];

                const headerRow = sheet.addRow(headers);
                headerRow.height = 65;
                headerRow.eachCell((cell, colNumber) => {
                    cell.font = { bold: true, size: 9 };
                    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } };
                    cell.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                    cell.alignment = (colNumber >= 11 && colNumber <= 41)
                    ? { textRotation: 90, horizontal: 'center', vertical: 'middle', wrapText: true }
                    : { horizontal: 'center', vertical: 'middle', wrapText: true };
                });

                sheet.getColumn(3).width = 25;
                for (let c = 11; c <= 44; c++) { if(![45,47].includes(c)) sheet.getColumn(c).width = 11.18; }
                sheet.getColumn(45).width = 21.5; sheet.getColumn(47).width = 21.5;

                let sl = 1;
                const sortedSubCenters = Object.keys(dataBySubCenter).sort();
                let hasData = false;

                for (const scName of sortedSubCenters) {
                    const scEmployees = dataBySubCenter[scName][categoryKey];
                    if (!scEmployees || scEmployees.length === 0) continue;

                    hasData = true;
                    const scRow = sheet.addRow([`Subcenter: ${scName}`]);
                    for (let i = 1; i <= 47; i++) {
                    const c = scRow.getCell(i);
                    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDAE3F3' } };
                    c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                    if (i === 1) c.font = { bold: true };
                    }
                    scRow.getCell(1).alignment = { vertical: 'middle', horizontal: 'left', wrapText: false };

                    let scTotalNet = 0;
                    scEmployees.forEach(d => {
                        const att = d.att || {};
                        const earn = d.earn || {};
                        const ded = d.ded || {};

                        // Check if archive has netPayment directly
                        const netPay = (d.netPayment !== undefined) ? getVal(d.netPayment) : (getVal(d.earn?.grossPayable) - getVal(d.ded?.totalDeduction));
                        scTotalNet += netPay;

                        const netBank = (d.netBankPayment !== undefined) ? getVal(d.netBankPayment) : (netPay - getVal(d.cashPayment));

                        const r = sheet.addRow([
                            sl++,
                            getStr(d.employeeId), getStr(d.name), getStr(d.designation), getStr(d.functionalRole), getStr(d.joiningDate),
                            getStr(d.project), getStr(d.projectOffice), getStr(d.reportProject), getStr(d.subCenter),
                            getVal(att.totalDays ?? d.totalDays), getVal(att.holidays ?? d.holidays), getVal(att.leave ?? d.availingLeave),
                            getVal(att.lwpDays ?? d.lwpDays), getVal(att.actualPresent ?? d.actualPresent), getVal(att.netPresent ?? d.netPresent), getVal(att.otHours),
                            getVal(d.previousSalary), getVal(earn.basic ?? d.basic), getVal(earn.others ?? d.others), getVal(earn.grossSalary ?? d.gross),
                            getVal(earn.maint ?? d.maint), getVal(earn.laptop ?? d.laptop), getVal(earn.othersAll ?? d.othersAllowance), getVal(earn.arrear ?? d.arrear), getVal(earn.food ?? d.food), getVal(earn.station ?? d.station), getVal(earn.hardship ?? d.hardship), getVal(earn.otAmount), getVal(earn.grossPayable ?? d.grossPayable),
                            0,
                            getVal(ded.lunch ?? d.lunch), getVal(ded.tds ?? d.tds), getVal(ded.bike ?? d.bike), getVal(ded.welfare ?? d.welfare),
                            getVal(ded.loan ?? d.loan), getVal(ded.vehicle ?? d.vehicle), getVal(ded.cpf ?? d.cpf), getVal(ded.adj ?? d.adj),
                            getVal(ded.attDed ?? d.attDed), getVal(ded.totalDeduction ?? d.totalDeduction),
                            getVal(d.cashPayment),
                            netBank,
                            netPay,
                            getStr(d.finalAccountNo || d.bankAccount), getStr(d.paymentType), getStr(d.remarksText || d.remarks)
                        ]);
                        r.getCell(1).alignment = { wrapText: false, vertical: 'middle', horizontal: 'center' };
                        r.eachCell((c, colNumber) => {
                            c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                            if (colNumber !== 1 && colNumber !== 3 && colNumber !== 47) {
                                c.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
                            }
                            if ((colNumber >= 18 && colNumber <= 30) || (colNumber >= 32 && colNumber <= 44)) c.numFmt = accountingFmt0;
                        });
                    });

                    const totRow = sheet.addRow(new Array(47).fill(''));
                    totRow.getCell(3).value = `Total for ${scName}`;
                    const netPayCell = totRow.getCell(44);
                    netPayCell.value = scTotalNet;
                    netPayCell.numFmt = accountingFmt0;
                    totRow.eachCell((c) => {
                        c.font = { bold: true };
                        c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' } };
                        c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                        c.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
                    });
                }

                if(!hasData) {
                    sheet.addRow(["No Data Available for this category."]);
                }
            }

            for (const [project, subCenters] of Object.entries(projectGroups)) {
                const workbook = new ExcelJS.Workbook();

                addSalarySheetTab(workbook, 'Salary Sheet', subCenters, 'active');

                /* ---------------- ADVICE SHEET (Active Only) ---------------- */
                const adviceSheet = workbook.addWorksheet('Advice', {
                    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
                });
                adviceSheet.pageSetup.printTitlesRow = '32:32';

                const consolidationMap = new Map();
                const allActiveEmployees = Object.values(subCenters).flatMap(sc => sc.active);

                allActiveEmployees.forEach(emp => {
                    if (emp.finalAccountNo && emp.finalAccountNo.trim() !== '') {
                        const key = String(emp.employeeId);
                        const netBank = (emp.netBankPayment !== undefined) ? getVal(emp.netBankPayment) : (getVal(emp.netPayment) - getVal(emp.cashPayment));

                        if (!consolidationMap.has(key)) {
                            consolidationMap.set(key, {
                                id: emp.employeeId, name: emp.name, designation: emp.designation,
                                account: emp.finalAccountNo, amount: 0
                            });
                        }
                        consolidationMap.get(key).amount += netBank;
                    }
                });

                // Holders (Active)
                allActiveEmployees.forEach(emp => {
                    if ((!emp.finalAccountNo || emp.finalAccountNo.trim() === '') && emp.holderId) {
                        const netBank = (emp.netBankPayment !== undefined) ? getVal(emp.netBankPayment) : (getVal(emp.netPayment) - getVal(emp.cashPayment));
                        if(consolidationMap.has(emp.holderId)) {
                            consolidationMap.get(emp.holderId).amount += netBank;
                        }
                    }
                });

                const writeTextRow = (rIdx, text, bold=false, size=14, merge=true) => {
                    const cell = adviceSheet.getRow(rIdx).getCell(1);
                    cell.value = text;
                    cell.font = { name: 'Calibri', size, bold };
                    cell.alignment = { vertical: 'top', wrapText: true };
                    if (merge) adviceSheet.mergeCells(rIdx, 1, rIdx, 6);
                };

                const totalLetterAmount = Array.from(consolidationMap.values()).reduce((sum, item) => sum + item.amount, 0);
                const totalAmountWords  = convertNumberToWords(totalLetterAmount);
                const today = new Date().toLocaleDateString('en-GB').replace(/\//g, '.');

                writeTextRow(1,  `Ref: MPL/TELECOM/Salary/${full}`, true);
                writeTextRow(2,  `Date: ${today}`, true);
                writeTextRow(4,  "To");
                writeTextRow(5,  "The Manager");
                writeTextRow(6,  "Dutch Bangla Bank Ltd.");
                writeTextRow(7,  "Banani Branch");
                writeTextRow(9,  `Subject: Salary expenses disbursement for the Month of ${quote}.`, true);
                writeTextRow(11, "Dear sir,");

                adviceSheet.mergeCells(13, 1, 19, 6);
                const paraCell = adviceSheet.getCell('A13');
                paraCell.value = `Please Transfer Tk.${totalLetterAmount.toLocaleString('en-IN')}/-Taka (in word: ${totalAmountWords}) to our following employee's bank account by debiting our CD Account No. 103.110.17302 in the name of Metal Plus Ltd. maintained with you. For better clarification we have provided you the soft copy of data through e-mail from id number saidul.islam@metalbd.biz , sender name Mr. Md. Saidul Islam and affirm you that soft copy of data is true and exact with hard copy of data submitted to you. For any deviation with soft copy and hard copy we will be held responsible. For any query please contact with Mr. Md. Saidul Islam; Mobile: 01766667498`;

                paraCell.font = { name: 'Calibri', size: 14 };
                paraCell.alignment = { wrapText: true, vertical: 'top' };

                for(let r=13; r<=19; r++) adviceSheet.getRow(r).height = 35;

                writeTextRow(21, "Thanking You,", false);

                adviceSheet.mergeCells(26, 1, 26, 3);
                adviceSheet.mergeCells(27, 1, 27, 3);
                adviceSheet.mergeCells(26, 4, 26, 6);
                adviceSheet.mergeCells(27, 4, 27, 6);

                const sigRowName = adviceSheet.getRow(26);
                const sigRowTitle = adviceSheet.getRow(27);
                sigRowName.height = 30;
                sigRowTitle.height = 30;

                const setSigStyle = (cell, bold) => {
                    cell.font = { name: 'Calibri', size: 14, bold: bold };
                    cell.alignment = { horizontal: 'left', vertical: 'top' };
                };

                sigRowName.getCell(1).value = "Engr. Sadid Jamil";
                setSigStyle(sigRowName.getCell(1), true);
                sigRowTitle.getCell(1).value = "Managing Director";
                setSigStyle(sigRowTitle.getCell(1), false);

                sigRowName.getCell(4).value = "Engr. Aminul Islam";
                setSigStyle(sigRowName.getCell(4), true);
                sigRowTitle.getCell(4).value = "Chairman";
                setSigStyle(sigRowTitle.getCell(4), false);

                adviceSheet.getRow(30).addPageBreak();

                const adviceHeader = adviceSheet.getRow(32);
                adviceHeader.values = ["SL", "ID", "Name", "Designation", "Account No", "Amount"];
                adviceHeader.height = 30;
                adviceHeader.eachCell((c) => {
                    c.font = { bold: true, size: 14 };
                    c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                    c.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
                    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } };
                });

                adviceSheet.getColumn(1).width = 6;
                adviceSheet.getColumn(2).width = 12;
                adviceSheet.getColumn(3).width = 28;
                adviceSheet.getColumn(4).width = 18;
                adviceSheet.getColumn(5).width = 20;
                adviceSheet.getColumn(6).width = 15;

                let advSl = 1;
                const finalAdviceList = Array.from(consolidationMap.values()).sort((a, b) => String(a.id).localeCompare(String(b.id)));

                finalAdviceList.forEach(item => {
                    const r = adviceSheet.addRow([advSl++, item.id, item.name, item.designation, item.account, item.amount]);
                    r.height = 25;
                    r.eachCell((c, colNumber) => {
                        c.font = { size: 14 };
                        c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                        c.alignment = { vertical: 'middle', horizontal: (colNumber === 3 ? 'left' : 'center'), wrapText: true };
                        if (colNumber === 6) c.numFmt = accountingFmt0;
                    });
                });

                const advTotRow = adviceSheet.addRow(['', '', 'Total', '', '', totalLetterAmount]);
                advTotRow.height = 30;
                advTotRow.getCell(6).numFmt = accountingFmt0;
                advTotRow.eachCell((c) => {
                    c.font = { bold: true, size: 14 };
                    c.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
                    c.border = { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} };
                });

                // 3. Salary Hold Sheet
                addSalarySheetTab(workbook, 'Salary Hold', subCenters, 'hold');

                // 4. Terminated/Resigned Sheet
                addSalarySheetTab(workbook, 'Terminated-Resigned', subCenters, 'separated');

                const buffer = await workbook.xlsx.writeBuffer();
                const safeName = project.replace(/[^a-z0-9]/gi, '_').substring(0, 30);
                zip.file(`${safeName}_${sheetMeta.monthYear}.xlsx`, buffer);
            }

            const blob = await zip.generateAsync({type:"blob"});
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = `Archive_${sheetMeta.monthYear}.zip`;
            a.click();

            customAlert("Success", "Past salary sheet downloaded successfully.");

        } catch (error) {
            console.error(error);
            customAlert("Error", "Download failed. " + error.message);
        }
    }
}