const axios = require('axios');

async function verifyPoliciesAPI() {
    const API_BASE = 'http://localhost:5000/api';
    const ts = Date.now();

    try {
        console.log("--- STARTING POLICY API VERIFICATION ---");

        // 1. Verify Leave Policy CRUD
        console.log("\n1. Testing Leave Policy CRUD...");
        const leavePolicyData = {
            name: `Test Leave ${ts}`,
            code: `TL${ts.toString().slice(-4)}`,
            daysAllowed: 15,
            applicableFor: 'All',
            genderRestriction: 'All',
            carryForward: true,
            requiresApproval: true,
            notes: 'Test policy generated by verification script',
            isActive: true
        };

        console.log("- Creating Leave Policy...");
        const createLeaveRes = await axios.post(`${API_BASE}/policies/leave`, leavePolicyData);
        const leaveId = createLeaveRes.data.id || createLeaveRes.data._id;
        console.log(`  Success! ID: ${leaveId}`);

        console.log("- Fetching Leave Policies...");
        const getLeaveRes = await axios.get(`${API_BASE}/policies/leave`);
        const createdLeave = getLeaveRes.data.find(p => p.name === leavePolicyData.name);
        if (createdLeave) {
            console.log("  Success! Found the created policy.");
        } else {
            throw new Error("Created leave policy not found in list!");
        }

        console.log("- Deleting Leave Policy...");
        await axios.delete(`${API_BASE}/policies/leave/${leaveId}`);
        console.log("  Success! Deleted.");


        // 2. Verify Salary Policy CRUD
        console.log("\n2. Testing Salary Policy CRUD...");
        const salaryPolicyData = {
            policyName: `Test Salary ${ts}`,
            joiningDateCutoff: '2024-01-01',
            effectiveFrom: '2024-01-01',
            festivalBonusPercentage: 50,
            incentiveBonusPercentage: 50,
            description: 'Test salary policy',
            isActive: true,
            slabs: [
                { slNo: 1, minGross: 3000, maxGross: 120000, basicPercentagePre: 50, basicPercentagePost: 35 },
                { slNo: 2, minGross: 120001, maxGross: null, basicPercentagePre: 30, basicPercentagePost: 30 }
            ]
        };

        console.log("- Creating Salary Policy...");
        const createSalaryRes = await axios.post(`${API_BASE}/policies/salary`, salaryPolicyData);
        const salaryId = createSalaryRes.data.id || createSalaryRes.data._id;
        console.log(`  Success! ID: ${salaryId}`);

        console.log("- Fetching Salary Policies...");
        const getSalaryRes = await axios.get(`${API_BASE}/policies/salary`);
        const createdSalary = getSalaryRes.data.find(p => p.policyName === salaryPolicyData.policyName);
        if (createdSalary) {
            console.log("  Success! Found the created salary policy.");
        } else {
            throw new Error("Created salary policy not found in list!");
        }

        console.log("- Testing Salary Lookup...");
        // Assuming there's a lookup endpoint or we can manually check logic
        // For now, let's just delete it
        console.log("- Deleting Salary Policy...");
        await axios.delete(`${API_BASE}/policies/salary/${salaryId}`);
        console.log("  Success! Deleted.");

        console.log("\n✅ ALL POLICY API VERIFICATIONS PASSED");

    } catch (err) {
        console.error("\n❌ VERIFICATION FAILED");
        if (err.response) {
            console.error(`Status: ${err.response.status}`);
            console.error("Data:", JSON.stringify(err.response.data, null, 2));
        } else {
            console.error(err.message);
        }
        process.exit(1);
    }
}

verifyPoliciesAPI();
